[versions]
android-compile = "android-31"
android-min = "24"
coroutines = "1.6.0"
coroutines-native = "1.6.0-native-mt!!"
jacoco = "0.8.7"
kotlin = "1.6.10"
ktor = "1.6.7"
wrappers = "1.0.1-pre.290-kotlin-1.6.10"

[libraries]
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.0" }
kotlin-wrappers = { module = "org.jetbrains.kotlin-wrappers:kotlin-extensions", version.ref = "wrappers" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-native = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-native" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.1" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

[plugins]
android-library = { id = "com.android.library", version = "7.0.4" }
android-publish = { id = "com.vanniktech.maven.publish", version = "0.18.0" }
atomicfu = { id = "kotlinx-atomicfu", version = "0.16.3" }
binary-compatibility-validator = { id = "binary-compatibility-validator", version = "0.8.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.6.10" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.8.0" }
one-eight = { id = "net.mbonnin.one.eight", version = "0.2" }
