[versions]
android-compile = "31"
coroutines = "1.6.4"
coroutines-native = "1.6.1-native-mt!!"
jacoco = "0.8.7"
kotlin = "1.7.20"
ktor = "2.1.2"

[libraries]
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-native = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-native" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

[plugins]
android-library = { id = "com.android.library", version = "7.3.0" }
android-publish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
atomicfu = { id = "kotlinx-atomicfu", version = "0.18.3" }
binary-compatibility-validator = { id = "binary-compatibility-validator", version = "0.8.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.10" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.12.0" }
one-eight = { id = "net.mbonnin.one.eight", version = "0.2" }
