name: CI
on:
  pull_request:
  # Trigger on merges to `main` to allow `gradle/gradle-build-action` runs to write their caches.
  # https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - run: ./gradlew assemble
      - run: ./gradlew check
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failure
          path: '**/build/reports/tests/'
          retention-days: 5

      - run: >
          ./gradlew
          -PVERSION_NAME=unspecified
          -PRELEASE_SIGNING_ENABLED=false
          publishToMavenLocal

      - run: ./gradlew jacocoTestReport

      - uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          junit_files: '**/build/test-results/**/*.xml'
          report_individual_runs: 'true'

      - uses: codecov/codecov-action@v4
