name: CI
on:
  pull_request:
  # Trigger on merges to `main` to allow `gradle/gradle-build-action` runs to write their caches.
  # https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

      - name: check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failure
          path: '**/build/reports/tests/'
          retention-days: 5

      - name: publishToMavenLocal
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -PVERSION_NAME=unspecified
            -PRELEASE_SIGNING_ENABLED=false
            publishToMavenLocal

      - name: jacocoTestReport
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoTestReport

      - uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          junit_files: '**/build/test-results/**/*.xml'
          report_individual_runs: 'true'

      - uses: codecov/codecov-action@v4
