name: GitHub Pages
on:
  push:
    branches:
      - main

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
            ~/.android/build-cache
            ~/.android/cache
          key: ${{ runner.os }}-gh-pages-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gh-pages-
            ${{ runner.os }}-

      - run: ./gradlew dokkaHtmlMultiModule

      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: build/gh-pages

      - run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
