name: GitHub Pages
on:
  push:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew dokkaHtmlMultiModule
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/gh-pages
