name: Publish
on:
  release:
    types:
      - published

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  publish:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew check
      - name: publish
        run: >
          ./gradlew
          -PVERSION_NAME='${{ github.ref_name }}'
          -PsigningInMemoryKey='${{ secrets.SIGNING_KEY }}'
          -PsigningInMemoryKeyPassword='${{ secrets.SIGNING_PASSWORD }}'
          -PmavenCentralUsername='${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}'
          -PmavenCentralPassword='${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}'
          publish
