name: Publish
on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew check
      - name: publish
        run: >
          ./gradlew
          -PVERSION_NAME='${{ github.ref_name }}'
          -PsigningInMemoryKey='${{ secrets.SIGNING_KEY }}'
          -PsigningInMemoryKeyPassword='${{ secrets.SIGNING_PASSWORD }}'
          -PmavenCentralUsername='${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}'
          -PmavenCentralPassword='${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}'
          publish
